// src/products.js

export const allProducts = [
    { id: 1, name: 'Rose Plant', price: '₹299', category: 'plants', imageUrl: 'Images/Red.webp' },
    { id: 2, name: 'Tulsi Plant', price: '₹199', category: 'plants', imageUrl: 'Images/Tulasi.webp' },
    { id: 3, name: 'Peace Lily, Spathiphyllum - Plant', price: '₹169', category: 'plants', imageUrl: 'Images/PeaceLily.webp' },
    { id: 4, name: 'Jasminum sambac', price: '₹169', category: 'plants', imageUrl: 'Images/Jasmin.jpg' },
    { id: 5, name: 'Parijat Tree', price: '₹359', category: 'plants', imageUrl: 'Images/Parijat.jpg' },
    { id: 6, name: 'Miniature Rose', price: '₹299', category: 'plants', imageUrl: 'Images/ButtonRose.jpg' },
    { id: 7, name: 'Damascus Rose', price: '₹299', category: 'plants', imageUrl: 'Images/Damascus Rose.jpg' },
    { id: 8, name: 'Jade plant ', price: '₹169', category: 'plants', imageUrl: 'Images/Jade.webp' },
    { id: 9, name: 'Rose (Peach) - Plant', price: '₹299', category: 'plants', imageUrl: 'Images/Baby.jpg' },
    { id: 10, name: 'Sunflower Seeds', price: '₹49', category: 'seeds', imageUrl: 'Images/sunflowerseed.webp' },
    { id: 11, name: 'Tomato Seeds', price: '₹29', category: 'seeds', imageUrl: 'Images/tomatoseed.webp' },
    { id: 12, name: 'Carrot Seeds', price: '₹39', category: 'seeds', imageUrl: 'Images/carrotseed.webp' },
    { id: 13, name: 'Spinach Seeds', price: '₹29', category: 'seeds', imageUrl: 'Images/spinachseeds.webp' },
    { id: 14, name: 'Lettuce Seeds', price: '₹29', category: 'seeds', imageUrl: 'Images/lettuceseeds.webp' },
    { id: 15, name: 'Cucumber Seeds', price: '₹39', category: 'seeds', imageUrl: 'Images/cucumberseeds.webp' },
    { id: 16, name: 'Bell Pepper Seeds', price: '₹29', category: 'seeds', imageUrl: 'Images/bellpepperseeds.webp' },
    { id: 17, name: 'Chili Pepper Seeds', price: '₹29', category: 'seeds', imageUrl: 'Images/pepperseeds.webp' },
    { id: 18, name: 'Ceramic Pot', price: '₹499', category: 'pots', imageUrl: 'Images/ceramicpots.jpg' },
    { id: 19, name: 'Plastic Pot', price: '₹99', category: 'pots', imageUrl: 'Images/PlasticPots.webp' },
    { id: 20, name: 'Terracotta Pot', price: '₹199', category: 'pots', imageUrl: 'Images/terracotapots.jpg' },
    { id: 21, name: 'Hanging Pot', price: '₹299', category: 'pots', imageUrl: 'Images/HangingPots.jpg' },
    { id: 22, name: 'Self-Watering Pot', price: '₹349', category: 'pots', imageUrl: 'Images/SelfWatering.webp' },
    { id: 23, name: 'Metal Stand', price: '₹399', category: 'pots', imageUrl: 'Images/stand.jpg' },
    { id: 24, name: 'Concrete Pot', price: '₹449', category: 'pots', imageUrl: 'Images/concretepot.jpg' },
    { id: 25, name: 'Wooden Pot', price: '₹299', category: 'pots', imageUrl: 'Images/woodenpot.jpg' },
  ];
  